# Generated by Django 3.1.7 on 2021-05-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='categories',
        ),
        migrations.AddField(
            model_name='category',
            name='auctions',
            field=models.ManyToManyField(blank=True, related_name='auction_Category', to='auctions.Auction_listing'),
        ),
    ]
