# Generated by Django 3.1.7 on 2021-05-03 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
