# Generated by Django 3.1.7 on 2021-05-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210504_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='auctions',
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='auctions.Category'),
        ),
    ]
