# Generated by Django 3.1.7 on 2021-04-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='auctions.comment'),
        ),
    ]
