# Generated by Django 3.1.7 on 2021-05-05 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210504_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='categories',
        ),
    ]
