# Generated by Django 3.1.7 on 2021-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_listing_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='auction_categories', to='auctions.Category'),
        ),
    ]
