# Generated by Django 3.1.7 on 2021-05-10 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210510_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(blank=True, related_name='auction_items', to='auctions.Auction_listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_maker', to=settings.AUTH_USER_MODEL),
        ),
    ]
