# Generated by Django 3.1.7 on 2021-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20210510_1037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
